services:
  server:
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_PORT: ${APP_PORT}
    ports:
      - 3000:3000
    container_name: agatha-server
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    container_name: agatha-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=agatha_laundry
      - POSTGRES_PASSWORD=cakra
