services:
  server:
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    container_name: agatha-server
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
